### ISSUE TITLE
Unable to run coloc.abf with beta and varbeta

### ISSUE THREAD

**Issue by boxiangliu** [chr1swallace/coloc#10]
Dear Chris,

I am trying to use coloc.abf with beta and varbeta. I received the following error: 

res=coloc.abf(dataset1=list(snp=gwas$snp,beta=gwas$beta,varbeta=gwas$varbeta,type="cc"),dataset2=list(snp=eqtl$snp,beta=eqtl$beta,varbeta=eqtl$varbeta,type="quant"))
Processing dataset
Error in process.dataset(d = dataset1, suffix = "df1") : 
  Must give, as a minimum, either (beta, varbeta, type) or (pvalues, MAF, N, type)

Since I have provided beta and varbeta, I am not sure why this error would occur. Could you help me on this? Thanks!

**Comment by chr1swallace** [comment]
Dear Boxiang,

you are missing MAF, but the error message is not informative.  If you 
update to the github version

devtools::install_github("chr1swallace/coloc")

you will get clearer feedback - apologies, I am still in the process of 
migrating those changes to CRAN.


On 21/06/16 02:25, Boxiang Liu wrote:
> Dear Chris,
>
> I am trying to use coloc.abf with beta and varbeta. I received the
> following error:
>
> res=coloc.abf(dataset1=list(snp=gwas$snp,beta=gwas$beta,varbeta=gwas$varbeta,type="cc"),dataset2=list(snp=eqtl$snp,beta=eqtl$beta,varbeta=eqtl$varbeta,type="quant"))
> Processing dataset
> Error in process.dataset(d = dataset1, suffix = "df1") :
> Must give, as a minimum, either (beta, varbeta, type) or (pvalues, MAF,
> N, type)
>
> Since I have provided beta and varbeta, I am not sure why this error
> would occur. Could you help me on this? Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chr1swallace/coloc/issues/10>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACFo6BgK4IzTnHtZNugqadQipyU7Kx9Kks5qNz2JgaJpZM4I6R51>.
>

-- 
http://chr1swallace.github.io

**Comment by anthony-aylward** [comment]
I have the same issue with the same error message on release 2.3-1 in R version 3.2.3. Is a MAF argument required for datasets with type "quant?"

**Comment by chesi** [comment]
Dear Chris,
I had the same issue and updated to the GitHub version.
Now I get:
Processing dataset
Error in process.dataset(d = dataset1, suffix = "df1") : 
  dataset df1: must give MAF or sdY for type quant

I though from the paper and the documentation that I needed beta and varbeta only. Do I need to provide MAFs, too? What is sdY?
Thanks!

**Comment by chesi** [comment]
When I provide a vector of MAFs, I get this error:
> my.res<- coloc.abf(dataset1,dataset2,MAF = maf1, p1 = 1e-04, p2 = 1e-04, p12 = 1e-05)
Processing dataset
Error in model.frame.default(formula = nvx ~ oneover, drop.unused.levels = TRUE) : 
  variable lengths differ (found for 'oneover')
> str(dataset1)
List of 3
 $ beta   : num [1:5187] 0.0479 0.0598 0.0832 0.055 0.0516 ...
 $ varbeta: num [1:5187] 1.79 7.59 9.46 1.8 1.8 ...
 $ type   : chr "quant"
> str(dataset2)
List of 3
 $ beta   : num [1:5187] 0.0393 0.2272 -0.1462 0.0407 0.0598 ...
 $ varbeta: num [1:5187] 1.07 4.5 5.05 1.06 1.06 ...
 $ type   : chr "quant"
> str(maf1)
 num [1:5187] 0.38 0.06 0.051 0.375 0.373 0.084 0.036 0.489 0.497 0.117 ...

**Comment by chr1swallace** [comment]
MAF is required because you don't supply sdY for either dataset, which is described in the help file as

> for a quantitative trait, the population standard deviation of the trait.  if not given, it can be estimated from the vectors of varbeta and MAF

The error you have comes from the model used to estimate that sdY.  I'm not sure why that fails, assuming you don't have any missing values, but I'd need access to your data to investigate.

**Comment by chr1swallace** [comment]
@boxiangliu sorry I missed your message.  If you give beta, varbeta, and either sdY or s (as appropriate if your trait is quantitative or case control), you shouldn't need MAF.

**Comment by anthony-aylward** [comment]
I also get the same error chesi gets when trying to run coloc.abf with beta varbeta, and MAF items in the input list, or with beta and verbena in the input list along with a global MAF argument. These data work fine when I provide their pvalues and N columns instead of beta and varbeta. 

Chris, would you be able to put up a vignette for simulating and running coloc.abf on data with beta, varbeta, and sdY, like the one that's currently online for pvalues, N, and MAF?

**Comment by chr1swallace** [comment]
That's a great idea. Will do!

On 18 November 2016 19:32:45 GMT+00:00, anthony-aylward <notifications@github.com> wrote:
>I also get the same error chesi gets when trying to run coloc.abf with
>beta varbeta, and MAF items in the input list, or with beta and verbena
>in the input list along with a global MAF argument. These data work
>fine when I provide their pvalues and N columns instead of beta and
>varbeta. 
>
>Chris, would you be able to put up a vignette for simulating and
>running coloc.abf on data with beta, varbeta, and sdY, like the one
>that's currently online for pvalues, N, and MAF?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/chr1swallace/coloc/issues/10#issuecomment-261620945

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chr1swallace** [comment]
Does the updated vignette at https://rawgit.com/chr1swallace/coloc/master/inst/doc/vignette.html help?
