### ISSUE TITLE
res$summary shows PP.H2.abf=1 AND PP.H4.abf=1

### ISSUE THREAD

**Issue by zainomarali** [chr1swallace/coloc#105]
Some background on what I am doing - due to the nature of our study a custom approach was taken to construct credible sets (i.e. without using SusieR). The approach we took gives us quite narrow credible sets and we have Bayes factors for all the variants in each credible set.

We are studying 9 different traits and we expect them to have some overlapping loci. We now have a long list of partially overlapping credible sets from different trait pairs. I wanted to use coloc to determine if the partially overlapping sets are truly colocalising or not.

We have Bayes factors for the variants in our credible set so I take the following approach: 

1) create vectors of Bayes factors for the 2 credible sets
2) subset to only those variants that are shared between the credible sets

This gives 2 equal length vectors of Bayes factors for the 2 loci, but I have had to throw away non-intersecting variants (I'm not sure if this is a problem?). 

Now it is trivial to simply apply coloc.bf_bf to these 2 vectors. In many cases this gives answers that make sense upon manual inspection.

But for a large number of cases the results summary shows that:

(PP.H2.abf=1 OR PP.H1.abf=1) AND PP.H4.abf=1.

How is this possible? How can 2 mutually exclusive hypotheses be completely certain?

**Comment by zainomarali** [comment]
Yes I can give you one example

a_vec = [4.567277e+26, 3.942818e+25]
b_vec = [7.097575e+45, 2.174417e+44]

if you run coloc.bf_bf on these vectors you should reproduce the behavior I described. Unfortunately I cannot share very complex examples with many markers or share my code directly as everything  is on a protected research network.

Thank you for your clarification on how to use coloc! I will ask our statistician for the other Bayes Factors (I was only provided BF for variants in credible sets)

**Comment by chr1swallace** [comment]
these values are huge. I think the issue is that the docs for coloc.bf_bf say these should be Bayes factors, but in fact they should be log​ Bayes factors.  Your example works if I use log(a), log(b).  I think the solution is that I update the docs - would you agree?
________________________________

**Comment by zainomarali** [comment]
Yes that sounds great! I will retry with log Bayes Factors and with the BFs for the entire region, thank you so much for your quick reply Chris!
