### ISSUE TITLE
Varbeta for eQTL and GWAS dataset

### ISSUE THREAD

**Issue by HKJ396** [chr1swallace/coloc#108]
Hi, I have  a question about varbeta which I take it to be the variance. I have found the variance for my GWAS results calculated from standard error. For example,I worked out the Standard deviation (SD) from standard error of the coefficient reported for each SNP result and then worked out variance from SD. Do I need to find the varbeta for the GTEX data in the same way? It only gives me standard error of the slope? So I am assuming I will need to find the variance/varbeta as well?

**Comment by chr1swallace** [comment]
varbeta is simply the square of the standard error of beta. you don't need the SD.

https://chr1swallace.github.io

________________________________
From: HKJ396 ***@***.***>
Sent: 28 November 2022 11:39
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] Varbeta for eQTL and GWAS dataset (Issue #108)


Hi, I have a question about varbeta which I take it to be the variance. I have found the variance for my GWAS results calculated from standard error. For example,I worked out the Standard deviation (SD) from standard error of the coefficient reported for each SNP result and then worked out variance from SD. Do I need to find the varbeta for the GTEX data in the same way? It only gives me standard error of the slope? So I am assuming I will need to find the variance/varbeta as well?

**Comment by HKJ396** [comment]
Thank you! I'm assuming I do SE^2 to find varbeta for the eqtl dataset too, since it gives me slope_se?

**Comment by chr1swallace** [comment]
Yes

https://chr1swallace.github.io
________________________________

**Comment by HKJ396** [comment]
I have my combined GWAS SNPs of interest and eQTL data with beta, varbeta, MAF, n. of people in study, SE, P value for my both the GWAS and the eQTL. I have also got a seperate LD matrix generated from my GWAS SNPs of interest. E.g. 

``
CHR_A   BP_A   SNP_B           R2       SNP_A  CHR_B         BP_B                                                                             
1     18054638 rs1572792:18054785:G:A     0.407277   rs35592535:18054638:GC:G      1     18054785
``

Do I need to reference my LD matrix separately in the coloc.susie function  or incorporate the LD values in my GWAS-eQTL dataset? Does the SNPs in the LD matrix, need to be in the same order in the GWAS-eQTL dataset?      

Thanks in advance
