### ISSUE TITLE
Input format for eQTL and GWAS analysis

### ISSUE THREAD

**Issue by s18692001** [chr1swallace/coloc#12]
Hi there,

I'm now trying to use this tool for my co-localization analysis of GWAS and eQTL. 
What are the required input formats of COLOC tool? Is there any tutorial for eQTL, GWAS analysis by this tool? Thanks!

Simon

**Comment by phuwanat** [comment]
Hello Simon,

I hope https://cran.r-project.org/web/packages/coloc/vignettes/vignette.html would help.
