### ISSUE TITLE
input for coloc.abf

### ISSUE THREAD

**Issue by billgreenwald** [chr1swallace/coloc#13]
Hi!  I was trying to run the coloc.abf function and got results I wasn't expecting, and wanted to check on the inputs.

The tutorial says to supply the variance of Beta in the varBeta vector.  Should this be a vector of the variance of Beta, the standard error of beta, the standard deviation of beta, or the square of the standard error of Beta?

Thanks!

**Comment by chr1swallace** [comment]
It should be the variance of beta, ie the square of its standard error.

On 12 July 2018 01:19:27 BST, Bill Greenwald <notifications@github.com> wrote:
>Hi!  I was trying to run the coloc.abf function and got results I
>wasn't expecting, and wanted to check on the inputs.
>
>The tutorial says to supply the variance of Beta in the varBeta vector.
>Should this be a vector of the variance of Beta, the standard error of
>beta, the standard deviation of beta, or the square of the standard
>error of Beta?
>
>Thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chr1swallace/coloc/issues/13

-- 
http://chr1swallace.github.io

**Comment by billgreenwald** [comment]
Thanks for the clarification, that fixed it.
