### ISSUE TITLE
coloc.abf error

### ISSUE THREAD

**Issue by maguileraf** [chr1swallace/coloc#141]
Hi Chris,
I am trying to use coloc for the first time but I keep getting this error:
Error in coloc.abf(dataset1 = D1, dataset2 = D2) : 
  dataset1 and dataset2 should contain the same snps in the same order, or should contain snp names through which the common snps can be identified

However, the snps in both lists are the same (see attached).  Any ideas on what could be the issue?
![Screenshot 2023-11-21 at 7 56 04 AM](https://github.com/chr1swallace/coloc/assets/49694113/9eed5962-2539-47f7-9334-7e3b7fd28fa8)
![Screenshot 2023-11-21 at 7 55 53 AM](https://github.com/chr1swallace/coloc/assets/49694113/d7957c29-8fa0-4528-9c94-438f6b53adeb)

**Comment by jjuhyunkim** [comment]
Did you figure out how to resolve this error? I encountered the same issue.
![스크린샷 2023-12-06 오전 1 11 56](https://github.com/chr1swallace/coloc/assets/131193680/05fdefa7-68d1-4578-aab9-766b5f382f42)

**Comment by chr1swallace** [comment]
I don't see this error. Could you share a minimal dataset that exhibits this issue?

--
https://chr1swallace.github.io
________________________________

**Comment by jjuhyunkim** [comment]
Thank you for your reply! ☺️ 

I have identified the issue during the data export process. 

The problem arises from using hg19 for dataset1 and hg38 for dataset2. I mistakenly did not replace the hg38 positions after liftovering variants from hg19.

**Comment by LLH0514** [comment]
I encountered the same issue.Error in coloc.abf(dataset1 = list(pvalues = input$pval_gwas, N = as.integer(input$samplesize_gwas),  : 
  dataset1 and dataset2 should contain the same snps in the same order, or should contain snp names through which the common snps can be identified.Did you figure out how to resolve this error?l use hg19 for dataset1 and hg19 for dataset2
