### ISSUE TITLE
"cc" and "quant" variables effect size

### ISSUE THREAD

**Issue by ariadnacilleros** [chr1swallace/coloc#149]
Hi, 

I have been reading some of the issues and I am pretty sure that I know the answer, but just in case I would like to confirm it. When we have a case-control GWAS, thus type = "cc", shall we set beta = log(OR) or beta = OR?            

Thank you so much!

Best, 

Ariadna

**Comment by chr1swallace** [comment]
Beta is log OR

--
https://chr1swallace.github.io
________________________________
From: Ariadna Cilleros Portet ***@***.***>
Sent: Monday, March 18, 2024 4:24:07 PM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] "cc" and "quant" variables effect size (Issue #149)


Hi,

I have been reading some of the issues and I am pretty sure that I know the answer, but just in case I would like to confirm it. When we have a case-control GWAS, thus type = "cc", shall we set beta = log(OR) or beta = OR?

Thank you so much!

Best,

Ariadna

**Comment by ariadnacilleros** [comment]
Got it! Thank you so much for the quick answer and the package.

Best,


Ariadna
