### ISSUE TITLE
Variants with zero variance raise an error

### ISSUE THREAD

**Issue by Zepeng-Mu** [chr1swallace/coloc#16]
In the estimation of sdY from varbeta, the variance of beta has to be a non-infinite non-zero value. In my eQTL mapping, there are some rare cases that P=1, therefore Z=0, and thus variance might also be 0. I am currently removing these few SNPs.
Is there a better way to handle this?
Many thanks

**Comment by chr1swallace** [comment]
I suggest replacing P=1 by P=1-eps, where eps is small (eg eps=2e-16)
