### ISSUE TITLE
Case proportion or case:control ratio?

### ISSUE THREAD

**Issue by Zepeng-Mu** [chr1swallace/coloc#17]
Hi,

While using `coloc.abf`, I got confused with the `s` parameter. In the document from R package, it says s is "for a case control dataset, the proportion of samples in dataset 1 that are cases". However, on other sources of documents, it says that we need "ratio of cases:controls".

Therefore, I just want to make sure which number should I actually use. Thank you so much!

**Comment by perezja** [comment]
Same question.

**Comment by chr1swallace** [comment]
It's the proportion, cases/(cases+controls).

I'll try and find mentions of ratio and fix. Thanks!
