### ISSUE TITLE
The use of case:control only when P is used

### ISSUE THREAD

**Issue by Zepeng-Mu** [chr1swallace/coloc#18]
Hi,

I am doing coloc between a GWAS and an eQTL dataset. GWAS is case-control in this case. For `type=cc`, `coloc.abf` also requires `s`, which is proportion of case, as an input. However, diving into the code it seems that `s` is only used when p-values are used, but not when beta and varbeta is provided (see the following line)

https://github.com/chr1swallace/coloc/blob/2ca77d0ad1815b7447aac3ebb86380a19f6c1c1f/R/claudia.R#L212

Therefore, is it possible to do coloc with beta and varbeta for case-control GWAS without giving `s`?

Thanks in advance!

**Comment by chr1swallace** [comment]
fixed - thanks
