### ISSUE TITLE
Data harmonization for MAF

### ISSUE THREAD

**Issue by daghli** [chr1swallace/coloc#20]
Hello,

I had several questions regarding data input and harmonization:
1. With regards to the MAF input, is this referring to the allele frequency of the 'effect allele' against which the beta is oriented?
2. Moreover, does coloc require data harmonization prior to analysis such that effect alleles are harmonized in the same direction? If so, I imagine a QC step would be to remove strand ambiguous alleles. 
3. If harmonization is indeed required as above, is the same harmonization necessary if supplying sd(Y) directly? The subtext here I suppose is does the sign of beta matter - from understanding of methodology I assume it does not. 

Thank you!

**Comment by chr1swallace** [comment]
1. it doesn't matter, calculations are symmetric in MAF (ie involve MAF*(1-MAF) )
2. No need for harmonization for standard coloc.abf assuming single causal variants. Things are more complicated for coloc.signals.
3. as for 2.
