### ISSUE TITLE
Running coloc.abf without MAF for case control GWAS- studies 

### ISSUE THREAD

**Issue by ndaga** [chr1swallace/coloc#21]
Hi Chris,

I am using new user of  coloc package.  I am using coloc.abf function for colocalisation analysis between hQTLs and GWAS summary statistics.

For one of the GWAS studies, it is a case control study and the parameters which are available are p-value. beta-values, var-beta but not MAF. At the moment, when I attempt to run the analysis, I get an error saying that for the type “cc”, I should have MAFs. 

In the vignette, its says I can run basic coloc.abf with regression coefficient and variance of these coefficients for each SNP. For, GWAS studies, I do have these parameters but I get the above error. 

My question is, is it possible to run “cc” type dataset without MAF’s with only  regression coefficient and variance of these coefficients.

**Comment by chr1swallace** [comment]
it is, and should now be fixed
