### ISSUE TITLE
coloc.signals without LD info

### ISSUE THREAD

**Issue by sylvain-moser** [chr1swallace/coloc#22]
Dear Chris, 

I am trying to run a colocalization analysis using the masking method in the condmask *development* branch. 

Because I don't have the info about the LD structure for any of the datasets, I used method="mask" (which to my understanding is made for cases when you don't have LD info). 

`GWAS_dataset=list(pvalues=GWAS_data$pval,N=36000,s=0.2,MAF=GWAS_data$minor_allele_frequency,beta=GWAS_data$beta,varbeta=GWAS_data$se,type="cc",snp=GWAS_data$rsid,LD=NULL) 
`
`eQTL_dataset=list(eQTL_df$pval_nominal,N=1000,MAF=eQTL_df$maf,beta=eQTL_df$slope,varbeta=eQTL_df$slope_se,type="quant",snp=eQTL_df$rs_id_dbSNP151_GRCh38p7,LD=NULL)
`
`col_analysis=coloc.signals(dataset1 = GWAS_dataset,dataset2 = eQTL_dataset,method ="mask",mode="iterative",p1 = 2.48e-5,p2=0,00161276,p12 = 0,00000626954)
`

I got two errors: 

1) If you don't specify LD=NULL in the dataset list but in the coloc.signal function, I get an error in finemap.signals at :
LD <- LD[D$snp, D$snp]
Error in LD[D$snp, D$snp] : incorrect number of dimensions

because dataset$LD is only defined at the beginning of coloc.signals if the LD argument is not NULL (default is NULL):
    if (!("LD" %in% names(dataset1)) & !is.null(LD)) 
        dataset1$LD <- LD

2) If I do specify LD=NULL in the dataset list, you then get an error in map_mask at:
 
friends <- apply(abs(LD[, sigsnps, drop = FALSE]) > sqrt(r2thr), 
            1, any, na.rm = TRUE) 

Error in abs(LD[, sigsnps, drop = FALSE]) 

Am I doing something wrong or is this a bug? 

Thanks for your help! 

Best 

Sylvain

**Comment by chr1swallace** [comment]
Dear Sylvain,

Thanks for your interest in coloc. 

You can't use mask without LD. It looks like I need to update the docs to make that clear, and also do better error checking of your inputs and informative error messages.

Thanks for noting!

Chris

⁣http://chr1swallace.github.io​
