### ISSUE TITLE
finemap.signals without beta and varbeta

### ISSUE THREAD

**Issue by silvakasela** [chr1swallace/coloc#24]
Dear Chris,

Can one use masking without providing beta and varbeta? Now when using (pvalues, MAF, N, type) as input, it throws an error in `coloc.signals()`:

```
Error in eval(jsub, SDenv, parent.frame()) : object 'varbeta' not found
```

The error message seems to originate from the `finemap.signals -> map_mask(D, LD, r2thr, sigsnps = names(hits))` function. Within that function absolute values of z-statistics are used (calculated from beta and varbeta), which can be estimated just based on the p-values too. Are the signed z-statistics that are the output of `finemap.signals()` used somewhere downstream in the `coloc.signals()` function? It seems that just the names of the output vector of `finemap.signals()` are used as an input to `coloc.process()`.

Related to use of `finemap.signals()` function in `coloc.signals()`, would it be possible to specify the independent variants/separate signals to use in `coloc.signals()`? For example, to specify the `fm1` object beforehand as an input for `coloc.signals()` and not estimating that within the function?

Thanks,
Silva

**Comment by chr1swallace** [comment]
Dear Silva,

I can't immediately work on this, but I also can't immediately see a reason not to do this. Thanks for the suggestion. I'll try and look at it in the next week or two and get back to you,

Chris

⁣http://chr1swallace.github.io​

**Comment by Zepeng-Mu** [comment]
I have the same question. Previously in coloc.abf for type="cc" I could use only P-value, MAF and N. But this is no longer working in coloc.signals, even if I use method="single".

**Comment by heinin** [comment]
Any updates on this? Best, Heini

**Comment by chr1swallace** [comment]
can you test the latest commit?  should be fixed

**Comment by heinin** [comment]
Thank you for the quick response! There seems to be a small typo which leads to an error now:

Line 94 in split.R:
wh <- hich.max(zdiff)

finemap_res <- finemap.signals(finemap_input, method="mask")
Error in hich.max(zdiff) : could not find function "hich.max"

**Comment by chr1swallace** [comment]
Ugh, I should have tested better, try now?

**Comment by heinin** [comment]
Works, thank you!
