### ISSUE TITLE
Issue with the `est_cond` function when running conditional coloc

### ISSUE THREAD

**Issue by adriaan-vd-graaf** [chr1swallace/coloc#29]
Dear Dr. Wallace, 

Thank you for the recent update to coloc, we're happy to  see that this popular method is still improving.

We're trying to run the new conditional coloc on some simulated data for benchmarking purposes, but cannot get the functions `finemap.signals()` and `coloc.signals()` to work. Both functions emit the following error:

```
Error in if (sum(use) == 1) { : missing value where TRUE/FALSE needed
Calls: finemap.signals -> map_cond -> est_cond
Execution halted
```

I'm attaching the code and summary statistics file to this message, so that you can reproduce the issue.
[code_conditional_coloc_github_issue.txt](https://github.com/chr1swallace/coloc/files/4559211/code_conditional_coloc_github_issue.txt)
[associations_github_issue.txt](https://github.com/chr1swallace/coloc/files/4559212/associations_github_issue.txt)

Unfortunately, the LD matrix is too large to share here, therefore I'm attaching it as a [link](https://surfdrive.surf.nl/files/index.php/s/p3L2vczHwmSfo8t).

Perhaps we're doing something wrong here?

Thank you for your time and best wishes
Adriaan

**Comment by chr1swallace** [comment]
Hi Adriaan, thank you for the very clear report and offering code and data!

I think the issue is that your snps are factors not character vectors. But investigating I also noticed that when sdY is missing, it was not being estimated by finemap.signals or coloc.signals.  I have added a warning for factor-type snps, and added estimation of sdY in those functions.  Could you download the current repo and try again?

**Comment by adriaan-vd-graaf** [comment]
Dear Dr Wallace, 

Thank you for the quick response!

I've downloaded the new repository, and adapted the code so that the SNP names are now characters.  This solves the issue in the `finemap.signals()` function. But unfortunately, it does solve the error in the `coloc.signals()` function. The output is the following: 

```
Error in process.dataset(d = dataset1, suffix = "df1") : 
  dataset df1: must give sdY for type quant, or, if sdY unknown, MAF and N so it can be estimated
Calls: coloc.signals -> coloc.detail -> as.data.table -> process.dataset
In addition: Warning messages:
1: In sdY.est(d$varbeta, d$MAF, d$N) :
  estimating sdY from maf and varbeta, please directly supply sdY if known
2: In sdY.est(d$varbeta, d$MAF, d$N) :
  estimating sdY from maf and varbeta, please directly supply sdY if known
```
Which makes me believe this issue is the same as issue #30. 

If I provide an sdY to the coloc objects, it does work so I will use that for now. 
I've provided the updated code that fails. 

Thank you for your time and best wishes,
Adriaan

[code_conditional_coloc_github_issue.txt](https://github.com/chr1swallace/coloc/files/4562929/code_conditional_coloc_github_issue.txt)

**Comment by chr1swallace** [comment]
This is odd, because it works for me. What does packageVersion("coloc") say?

**Comment by adriaan-vd-graaf** [comment]
The version is outputs is 4.0.0. I've downloaded the `condmask` branch of the repository. According to github, the last update was 18 days ago. Should I be using the `condmask` branch?

Thanks again for the support :-)

**Comment by chr1swallace** [comment]
Please try the master branch now.

Also, if you do know sdY, please supply it instead of using an estimate that is incorrect.

⁣http://chr1swallace.github.io​

**Comment by adriaan-vd-graaf** [comment]
Thank you! that did the trick! 
We will be supplying the sdY in our simulations for better results.

Thank you again :-)
