### ISSUE TITLE
coloc.signals requires sdY even when MAF and N is given

### ISSUE THREAD

**Issue by Zepeng-Mu** [chr1swallace/coloc#30]
Hi,

I am trying to run `coloc.signals` on my dataset. For my QTL dataset, I supplied N, beta, varbeta, type, LD, MAF, snp, method. However I got this output:
```
PP.H0.abf PP.H1.abf PP.H2.abf PP.H3.abf PP.H4.abf 
7.19e-146 2.97e-146  6.63e-01  2.74e-01  6.38e-02 
[1] "PP abf for shared variant: 6.38%"
Error in process.dataset(d = dataset1, suffix = "df1") : 
  dataset df1: must give sdY for type quant, or, if sdY unknown, MAF and N so it can be estimated
In addition: Warning message:
In sdY.est(d$varbeta, d$MAF, d$N) :
  estimating sdY from maf and varbeta, please directly supply sdY if known
```
It is strange to be because PP4 can be calculated and I got the warning message "estimating sdY from maf and varbeta, please directly supply sdY if known", just like what I got using `coloc.abf`. But I also got the error message "dataset df1: must give sdY for type quant, or, if sdY unknown, MAF and N so it can be estimated". I did not see this when using coloc.abf.

Thanks so much!

**Comment by Zepeng-Mu** [comment]
I also found that this error only happens when I use `method = "cond"` for dataset 1.

**Comment by chr1swallace** [comment]
Hi Zepeng, investigating #29 I realised that coloc.signals was not estimating sdY when not supplied. Could you please download the new repo and try again?

**Comment by Zepeng-Mu** [comment]
Hi, thank you for the quick response!
I think it is working now.
I also have a kind of unrelated question. Do I always have to supply an LD matrix, or is it just needed for "cond" method?

**Comment by chr1swallace** [comment]
You need it for either cond or mask, but not single.

⁣http://chr1swallace.github.io​
