### ISSUE TITLE
Implementing coloc's conditional analysis in moloc

### ISSUE THREAD

**Issue by gentryjl** [chr1swallace/coloc#31]
Hello,

I am trying to implement the new conditional analysis included in coloc to moloc. I am not very familiar with the statistics that you use, so I am somewhat blindly adapting coloc scripts to work with moloc. I hope to get your input as to whether or not my proposed code makes sense and whether or not there are any statistical problems with applying coloc's conditional analysis to moloc.

If I understand coloc.signals correctly, you first identify independent variants associated with the individual traits (finemap.signals) and then calculate the estimates conditioning on these independent signals (est_all_cond). Then you perform the Bayesian colocalization on every combination of the conditional estimates (coloc.detail). If colocalizing on the conditional estimates of all traits, coloc.process does not do much other than reformat the data for easier interpretation.

Does it make sense then to replace coloc.detail and coloc.process with moloc's moloc_test function? I've attached some code that I adapted from coloc.signals that implements this approach (just replace .txt with .R). Are there any statistical problems with doing this?

Let me know if I should post this on moloc's github instead.

Best,
James

[moloc.signals.txt](https://github.com/chr1swallace/coloc/files/4709188/moloc.signals.txt)

**Comment by chr1swallace** [comment]
I'm afraid I am not very familiar with moloc, so I suggest you ask the moloc authors.
