### ISSUE TITLE
coloc.abf: priors p value and making sense of output?

### ISSUE THREAD

**Issue by sariya** [chr1swallace/coloc#32]
hi chris,

I'm using GWAS summary stats and eQTL to conduct coloc analysis. I use `coloc.abf` using variance and beta for SNPs at default function parameters. 

Upon analysing, I check output, for example, SNP1 that has `SNP.PP.H4` of 1.13E-04. But in GWAS SNP has P-value of 0.72 and in eQTL, SNP has P-value of 0.08.

I find it odd that P-values from separate analysis are so big (that is non significant), yet the posterior probability is so low (that is more significant).

Also, the defaults for priors are as follows:
p1 prior probability a SNP is associated with trait 1, default 1e-4
p2 prior probability a SNP is associated with trait 2, default 1e-4
p12 prior probability a SNP is associated with both traits, default 1e-5

I'm sorry, but how are these used?  

Would you be able to shed some light on these two questions?

I'm using R4.0 and coloc_3.2-1

**Comment by chr1swallace** [comment]
Hi Sanjeev,

Thanks for your interest in coloc.

I think you are confusing p values (probability of data as or more extreme as that observed under a null hypothesis) with prior and posterior probabilities (probability of a given hypothesis, before or after seeing the data). 

I think the most careful description of how coloc works I have written is in this paper https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008720 - can I suggest you read that and get back to me if needed? 

C

⁣http://chr1swallace.github.io​

**Comment by sariya** [comment]
Got it, thank you
