### ISSUE TITLE
error when using finemap.abf() function

### ISSUE THREAD

**Issue by schavezchavez** [chr1swallace/coloc#37]
Dear Chris,
My apologies for disturbing you again.
I am trying to run the finemap.abf() function, but keep getting an error which yields NA's in the SNP.PP column (see below).
The script was running fine when using a small set of snps (169), but now i wanted to run on a whole chromosome (552K SNP's) and it gives me this error. Only thing that changed in the input file were the headers(which were then adjusted in the dataset=parameters and that SNP ID is now CPTID instead of rsid).
Do you know perhaps how to solve this.

Thank you veru much in advance.

Kind regards,

Sergio

![image](https://user-images.githubusercontent.com/61784115/95108504-a35a4880-073b-11eb-9cd1-0dc0efe1e7c2.png)

**Comment by chr1swallace** [comment]
Please see https://chr1swallace.github.io/coloc/articles/a02_data.html on preparing your data
