### ISSUE TITLE
Simulation example on coloc conditioning vignette not working

### ISSUE THREAD

**Issue by JesseRop** [chr1swallace/coloc#38]
Dear Coloc developers, 

Thank you for creating such a helpful user friendly tool. I aim to use the new feature on testing for colocalization on multiple SNPs in a locus between traits and I am trialing the examples on your vignette (https://chr1swallace.github.io/coloc/articles/a05_conditioning.html) on this but the script to simulate a dataset is not working. I will be grateful if you could look into this.

```
library(mvtnorm)
simx <- function(nsnps,nsamples,S,maf=0.1) {
    mu <- rep(0,nsnps)
    rawvars <- rmvnorm(n=nsamples, mean=mu, sigma=S)
    pvars <- pnorm(rawvars)
    x <- qbinom(1-pvars, 2, maf)
}


sim.data <- function(nsnps=50,nsamples=200,causals=floor(nsnps/2),nsim=1) {
  cat("Generate",nsim,"small sets of data\n")
  ntotal <- nsnps * nsamples * nsim
  S <- (1 - (abs(outer(1:nsnps,1:nsnps,`-`))/nsnps))^4
  X1 <- simx(nsnps,ntotal,S)
  X2 <- simx(nsnps,ntotal,S)
  Y1 <- rnorm(ntotal,rowSums(X1[,causals,drop=FALSE]/2),2)
  Y2 <- rnorm(ntotal,rowSums(X2[,causals,drop=FALSE]/2),2)
  colnames(X1) <- colnames(X2) <- paste("s",1:nsnps,sep="")
  df1 <- cbind(Y=Y1,X1)
  df2 <- cbind(Y=Y2,X2)
  if(nsim==1) {
    return(new("simdata",
               df1=as.data.frame(df1),
               df2=as.data.frame(df2)))
  } else {
    index <- split(1:(nsamples * nsim), rep(1:nsim, nsamples))
    objects <- lapply(index, function(i) new("simdata", df1=as.data.frame(df1[i,]),
                                             df2=as.data.frame(df2[i,])))
    return(objects)
  }
}

set.seed(46411)
data <- sim.data()
```

**Comment by chr1swallace** [comment]
Could you please explain "not working"?

⁣http://chr1swallace.github.io​

**Comment by JesseRop** [comment]
When I run the script as is on R after installing mvtnorm package, I am not able to generate a simulated dataset but I get this error instead;

```
Error in getClass(Class, where = topenv(parent.frame())): “simdata” is not a defined class
Traceback:

1. sim.data()
2. new("simdata", df1 = as.data.frame(df1), df2 = as.data.frame(df2))   # at line 21-23 of file <text>
3. getClass(Class, where = topenv(parent.frame()))
4. stop(gettextf("%s is not a defined class", dQuote(Class)), domain = NA)
```

**Comment by chr1swallace** [comment]
Have you loaded the coloc package by this point?

⁣http://chr1swallace.github.io​

**Comment by JesseRop** [comment]
Yes, 
Both coloc and mvtnorm are loaded as you can see from the sessioninfo() output below

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS/LAPACK: /software/hgi/installs/anaconda3/envs/nextflow20/lib/libopenblasp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_GB.utf8        LC_COLLATE=en_GB.utf8    
 [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=en_GB.utf8   
 [7] LC_PAPER=en_GB.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] coloc_4.0-4       viridis_0.5.1     viridisLite_0.3.0 snpStats_1.36.0  
[5] Matrix_1.2-18     survival_3.1-8    remotes_2.1.1     mvtnorm_1.1-1    

loaded via a namespace (and not attached):
 [1] pbdZMQ_0.3-3        tidyselect_1.1.0    repr_1.1.0         
 [4] purrr_0.3.4         splines_3.6.1       lattice_0.20-40    
 [7] pcaPP_1.9-73        colorspace_2.0-0    vctrs_0.3.5        
[10] generics_0.1.0      stats4_3.6.1        htmltools_0.5.0    
[13] base64enc_0.1-3     rlang_0.4.8         pkgbuild_1.1.0     
[16] BMA_3.18.12         pillar_1.4.6        glue_1.4.2         
[19] withr_2.3.0         BiocGenerics_0.32.0 uuid_0.1-4         
[22] lifecycle_0.2.0     robustbase_0.93-6   zlibbioc_1.32.0    
[25] munsell_0.5.0       gtable_0.3.0        leaps_3.1          
[28] evaluate_0.14       inline_0.3.17       callr_3.5.1        
[31] ps_1.4.0            parallel_3.6.1      curl_4.3           
[34] fansi_0.4.1         DEoptimR_1.0-8      IRdisplay_0.7.0    
[37] scales_1.1.1        BiocManager_1.30.10 IRkernel_1.1       
[40] jsonlite_1.7.1      gridExtra_2.3       ggplot2_3.3.2      
[43] digest_0.6.27       processx_3.4.5      dplyr_1.0.2        
[46] grid_3.6.1          rprojroot_2.0.2     cli_2.2.0          
[49] tools_3.6.1         magrittr_2.0.1      tibble_3.0.4       
[52] rrcov_1.5-5         crayon_1.3.4        pkgconfig_2.0.3    
[55] ellipsis_0.3.1      data.table_1.13.2   prettyunits_1.1.1  
[58] assertthat_0.2.1    R6_2.5.0            compiler_3.6.1  
```

**Comment by chr1swallace** [comment]
Ok, I'll take a look tomorrow.

Meanwhile, you can define the class with

setClass("simdata", representation(df1="data.frame",df2="data.frame"))setValidity("simdata", function(object) { n <- nrow(object@df1) if(nrow(object@df2)!=n) return("nrow of '@df1' should equal nrow of '@df2'")})setMethod("show", signature="simdata", function(object) { cat("pair of simulated datasets, with",ncol(object@df1)-1,"SNPs and",nrow(object@df1),"samples.\n")})

Taken from https://github.com/chr1swallace/coloc/blob/master/vignettes/simdata.Rmd if my phone email messes it up.

⁣http://chr1swallace.github.io​

**Comment by JesseRop** [comment]
Many thanks for your very prompt attention on this and for the workaround which has fixed it.

Best,
Jesse

**Comment by epistudent** [comment]
> Ok, I'll take a look tomorrow. Meanwhile, you can define the class with setClass("simdata", representation(df1="data.frame",df2="data.frame"))setValidity("simdata", function(object) { n <- nrow(object@df1) if(nrow(object@df2)!=n) return("nrow of '@df1' should equal nrow of '@df2'")})setMethod("show", signature="simdata", function(object) { cat("pair of simulated datasets, with",ncol(object@df1)-1,"SNPs and",nrow(object@df1),"samples.\n")}) Taken from https://github.com/chr1swallace/coloc/blob/master/vignettes/simdata.Rmd if my phone email messes it up. ⁣[http://chr1swallace.github.io​](http://chr1swallace.github.io%E2%80%8B)
> […](#)
> On 3 Dec 2020, 22:27, at 22:27, JesseRop ***@***.***> wrote: Yes, Both coloc and mvtnorm are loaded as you can see from the sessioninfo() output below ``` R version 3.6.1 (2019-07-05) Platform: x86_64-conda_cos6-linux-gnu (64-bit) Running under: Ubuntu 18.04.5 LTS Matrix products: default BLAS/LAPACK: /software/hgi/installs/anaconda3/envs/nextflow20/lib/libopenblasp-r0.3.7.so locale: [1] LC_CTYPE=en_GB.utf8 LC_NUMERIC=C [3] LC_TIME=en_GB.utf8 LC_COLLATE=en_GB.utf8 [5] LC_MONETARY=en_GB.utf8 LC_MESSAGES=en_GB.utf8 [7] LC_PAPER=en_GB.utf8 LC_NAME=C [9] LC_ADDRESS=C LC_TELEPHONE=C [11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C attached base packages: [1] stats graphics grDevices utils datasets methods base other attached packages: [1] coloc_4.0-4 viridis_0.5.1 viridisLite_0.3.0 snpStats_1.36.0 [5] Matrix_1.2-18 survival_3.1-8 remotes_2.1.1 mvtnorm_1.1-1 loaded via a namespace (and not attached): [1] pbdZMQ_0.3-3 tidyselect_1.1.0 repr_1.1.0 [4] purrr_0.3.4 splines_3.6.1 lattice_0.20-40 [7] pcaPP_1.9-73 colorspace_2.0-0 vctrs_0.3.5 [10] generics_0.1.0 stats4_3.6.1 htmltools_0.5.0 [13] base64enc_0.1-3 rlang_0.4.8 pkgbuild_1.1.0 [16] BMA_3.18.12 pillar_1.4.6 glue_1.4.2 [19] withr_2.3.0 BiocGenerics_0.32.0 uuid_0.1-4 [22] lifecycle_0.2.0 robustbase_0.93-6 zlibbioc_1.32.0 [25] munsell_0.5.0 gtable_0.3.0 leaps_3.1 [28] evaluate_0.14 inline_0.3.17 callr_3.5.1 [31] ps_1.4.0 parallel_3.6.1 curl_4.3 [34] fansi_0.4.1 DEoptimR_1.0-8 IRdisplay_0.7.0 [37] scales_1.1.1 BiocManager_1.30.10 IRkernel_1.1 [40] jsonlite_1.7.1 gridExtra_2.3 ggplot2_3.3.2 [43] digest_0.6.27 processx_3.4.5 dplyr_1.0.2 [46] grid_3.6.1 rprojroot_2.0.2 cli_2.2.0 [49] tools_3.6.1 magrittr_2.0.1 tibble_3.0.4 [52] rrcov_1.5-5 crayon_1.3.4 pkgconfig_2.0.3 [55] ellipsis_0.3.1 data.table_1.13.2 prettyunits_1.1.1 [58] assertthat_0.2.1 R6_2.5.0 compiler_3.6.1 ``` -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#38 (comment)](https://github.com/chr1swallace/coloc/issues/38#issuecomment-738375991)

Hi Chris, I had the same problem as Jesse. but when I set up the class, the problem was solved. Could you update in the website so others could avoid getting stuck with that? 

Best, 
Yan

**Comment by chr1swallace** [comment]
Dear Yan,

I have updated the vignettes, they no longer require this class.
Hopefully that fixes everything for you.

C
