### ISSUE TITLE
error using finemap.signals for method 'cond'

### ISSUE THREAD

**Issue by Poojaa-srinivasa** [chr1swallace/coloc#41]
Hi,
I'm running finemap.signals to use the 'cond' method and getting the following error 

`approximating linear analysis of binary trait
 Error in if (sum(use) == 1) { : missing value where TRUE/FALSE needed`

I tried to fix this but this is causing other issues. I kindly request you to look into this issue.

Many thanks,
Pooja

**Comment by chr1swallace** [comment]
Hi Pooja, 

I have deprecated finemap.signals, partly because of these numerical errors and partly because theoretically the new SuSiE appraoch seems better than conditioning.  Please see https://chr1swallace.github.io/coloc/articles/a06_SuSiE.html
