### ISSUE TITLE
Confusing results when using beta and varbeta in coloc.abf()

### ISSUE THREAD

**Issue by JFF1594032292** [chr1swallace/coloc#43]
Hi! I was new to using coloc and it's really a great tool. However, I met some confusing results.
I read the reference in https://chr1swallace.github.io/coloc/reference/coloc.abf.html , and the coloc.abf() recommend to using beta, varbeta, N, MAF when sdY unknown. But when I test this function with the same dataset1 and dataset2 (which expect a PPH4=1), the result was not as expected:
`l_gwas=list(N=eqtl$N,MAF=eqtl$MAF,beta=gwas$b,varbeta=gwas$SE,type="quant",snp=as.character(gwas$SNP))`
`coloc.abf(l_gwas,l_gwas)`
![image](https://user-images.githubusercontent.com/49577864/105578864-1dcbd880-5dbe-11eb-9510-0b3b203263a5.png)
And I got exactly the same results when add p values columns.

The interesting things is, when I using only N, MAF, p values columns, I got the right result!
`l_gwas=list(N=gwas$N,pvalues=gwas$p,MAF=gwas$MAF,type="quant",snp=as.character(gwas$SNP))`
`res=coloc.abf(l_gwas,l_gwas)`
![image](https://user-images.githubusercontent.com/49577864/105579094-54eeb980-5dbf-11eb-9ff8-f172d75753f1.png)

According to the article and reference documentation,  the beta and varbeta should be used first. However, the result shows that I should only provide p values.
By the way, no PPH4 better than 0.005 when I use "beta, varbeta, N, MAF" to conduct a colocalization the a real GWAS summary and eQTL summary data. Which seems something wrong.

All program was running on R3.6.1 and coloc 4.0-4. Thank you for your help.

Jiang Feng

**Comment by chr1swallace** [comment]
Are you passing varbeta or se beta? Your column name looks like se.

⁣http://chr1swallace.github.io​

**Comment by JFF1594032292** [comment]
Oh.........right, I used the se rather than varbeta. The results is consistent with expectation after correct the varbeta. Thanks for your quickly response! 
I really need to be more careful later.......

**Comment by chr1swallace** [comment]
This is a common error. Is there something I could do to make it clearer?

⁣http://chr1swallace.github.io​

**Comment by JFF1594032292** [comment]
That's probably because most association studies give the standard error directly rather than variance (e.g. GTEX and most GWAS summary data). Maybe you can add a tip to "varbeta" in the reference documentation to remind some careless people.

**Comment by Cobbybaby** [comment]
> Hi! I was new to using coloc and it's really a great tool. However, I met some confusing results.
> I read the reference in https://chr1swallace.github.io/coloc/reference/coloc.abf.html , and the coloc.abf() recommend to using beta, varbeta, N, MAF when sdY unknown. But when I test this function with the same dataset1 and dataset2 (which expect a PPH4=1), the result was not as expected:
> `l_gwas=list(N=eqtl$N,MAF=eqtl$MAF,beta=gwas$b,varbeta=gwas$SE,type="quant",snp=as.character(gwas$SNP))`
> `coloc.abf(l_gwas,l_gwas)`
> ![image](https://user-images.githubusercontent.com/49577864/105578864-1dcbd880-5dbe-11eb-9510-0b3b203263a5.png)
> And I got exactly the same results when add p values columns.
> 
> The interesting things is, when I using only N, MAF, p values columns, I got the right result!
> `l_gwas=list(N=gwas$N,pvalues=gwas$p,MAF=gwas$MAF,type="quant",snp=as.character(gwas$SNP))`
> `res=coloc.abf(l_gwas,l_gwas)`
> ![image](https://user-images.githubusercontent.com/49577864/105579094-54eeb980-5dbf-11eb-9ff8-f172d75753f1.png)
> 
> According to the article and reference documentation, the beta and varbeta should be used first. However, the result shows that I should only provide p values.
> By the way, no PPH4 better than 0.005 when I use "beta, varbeta, N, MAF" to conduct a colocalization the a real GWAS summary and eQTL summary data. Which seems something wrong.
> 
> All program was running on R3.6.1 and coloc 4.0-4. Thank you for your help.
> 
> Jiang Feng

Hi 
  I am runing COLOC  soem times, but  have question. so I want to disscuss it. in COLOC, does GTEx need to be processed? Is the analysis performed by gene? such as , SNPs within this region and SNPs from one gene in GTEx?

**Comment by chr1swallace** [comment]
Yes. If you think about what hypotheses you are testing, they are
presumably about whether there are shared genetic causes for the
expression of one gene and some other trait.  Coloc only tests a pair
of traits at once, so one of the datasets you pass should be for one
gene, and the other for the other trait.

**Comment by Cobbybaby** [comment]
> Yes. If you think about what hypotheses you are testing, they are presumably about whether there are shared genetic causes for the expression of one gene and some other trait. Coloc only tests a pair of traits at once, so one of the datasets you pass should be for one gene, and the other for the other trait.
> […](#)
> On Tue, 2021-01-26 at 01:11 -0800, Pam wrote: in COLOC, does GTEx need to be processed? Is the analysis performed by gene? such as , SNPs within this region and SNPs from one gene in GTEx?

Thank you for your reply, I have a better understanding of it. so I want to install the new version coloc4. However，I have another question about two methods:
1>
In GWAS summary，Do I need to set some independent region by LD? such as ,   for the SNPs with p < 5e-8, I will use PLINK LD-pruned r2 <0.1 , so I will get tag SNP , then Tag SNP’ region was identified by r2 > 0.8 for each index LD-pruned SNPs. Finally , I extend the region adapted the colocalization study for the 500-kb window around each Tag SNP region.  
2>
I just merge GWAS summary with GTEx  by chr_bp_id，then to run coloc.  I think the region is the min base postion(BP) of SNP  to max BP in each gene in GTEx. 
I do not know the difference between them or which is best, it is confusing me for a long time ,help me. Thanks you.

**Comment by chr1swallace** [comment]
method 2 sounds ok, depending how large those regions are.

otherwise, use method 1, but you can only take genes where most of your
snps in your gwas region have eqtl statistics

**Comment by Cobbybaby** [comment]
> method 2 sounds ok, depending how large those regions are. otherwise, use method 1, but you can only take genes where most of your snps in your gwas region have eqtl statistics
> […](#)
> On Wed, 2021-01-27 at 05:38 -0800, Pam wrote: > Yes. If you think about what hypotheses you are testing, they are > presumably about whether there are shared genetic causes for the > expression of one gene and some other trait. Coloc only tests a > pair of traits at once, so one of the datasets you pass should be > for one gene, and the other for the other trait. > … > On Tue, 2021-01-26 at 01:11 -0800, Pam wrote: in COLOC, does GTEx > need to be processed? Is the analysis performed by gene? such as , > SNPs within this region and SNPs from one gene in GTEx? > Thank you for your reply, I have a better understanding of it. so I want to install the new version coloc4. However，I have another question about two methods: 1> In GWAS summary，Do I need to set some independent region by LD? such as , for the SNPs with p < 5e-8, I will use PLINK LD-pruned r2 <0.1 , so I will get tag SNP , then Tag SNP’ region was identified by r2 > 0.8 for each index LD-pruned SNPs. Finally , I extend the region adapted the colocalization study for the 500-kb window around each Tag SNP region. 2> I just merge GWAS summary with GTEx by chr_bp_id，then to run coloc. I think the region is the min base postion(BP) of SNP to max BP in each gene in GTEx. I do not know the difference between them or which is best, it is confusing me for a long time ,help me. Thanks you. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for your advise. In method2 , I think it is no meaning to test coloc in the region because there is no any Significant SNP (p > 5e-8 ) in these regions unless choosing a loose threshold ( 1e-6). In method 1, it may contain two causal variants  and  in "depending the regions ",  it means  if the region is too big or too small , the test mar be failure? I think the second kind of test is more purposeful.  Is there any other good way?  you know coloc need test a LD region, and coloc4 can relax the single causal variant assumption, so I think the second signal in GWAS does not need to be removed by LD in one region. just my understant. Thank you a lot.

**Comment by hel3na33** [comment]
Hi,

Thanks for creating this amazing tool. As it's the first time I'm running it, I have a naive question after reading the documentation and running the coloc.abf() in two different ways. I am a little bit confused as to what exactly needs to be included in the datasets;

I have both quantitative and case-control outcomes. I realise from the documentation that for the type=cc, the ideal columns of the dataset are: snp (preferrably so it can match the datasets), beta, varbeta, N, pvalues, MAF, type and "s". 

For the type=quant, I need all of the above -excluding "s"- if the sdY is unknown.  

**1) So firstly, what I am confused about, is of what is absolutely necessary for coloc.abf() to run (apart from the snp which is not necessary but it's ideal so it can match the datasets)?

2) And now the naive question; When you are referring to "varbeta", are you simply referring to (s.e)^2? I tried running the function without varbeta in both datasets and it runs.. But it would be good to know if I can easily find it or measure it..** 

Thank you very much in advance

**Comment by chr1swallace** [comment]
I have created https://chr1swallace.github.io/coloc/articles/a02_data.html which should help

**Comment by Captain-Pam** [comment]
Hi,
Thank your for your tool. I have been using COLOC to analyse data recently, but I have a question, do I need to flip either GWAS summary's allele to be consistent with the other one before COLOC analysis?&nbsp;i.e. beta modified to -beta.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris ***@***.***&gt;; 
发送时间: 2021年1月26日(星期二) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chr1swallace/coloc] Confusing results when using beta and varbeta in coloc.abf() (#43)





 Yes. If you think about what hypotheses you are testing, they are
 presumably about whether there are shared genetic causes for the
 expression of one gene and some other trait.  Coloc only tests a pair
 of traits at once, so one of the datasets you pass should be for one
 gene, and the other for the other trait.
 
 On Tue, 2021-01-26 at 01:11 -0800, Pam wrote:
 &gt; in COLOC, does GTEx need to be processed? Is the analysis performed
 &gt; by gene? such as , SNPs within this region and SNPs from one gene in
 &gt; GTEx?

**Comment by chr1swallace** [comment]
that depends which coloc function you are using?
________________________________

**Comment by Captain-Pam** [comment]
Hi,
Thank you for your reply.
I am performing Colocalization analysis using&nbsp;coloc::coloc.abf（）function.&nbsp;
I noticed this has an upgrade,but I haven't used this function coloc.susie() function. Does all of this require a flip?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chr1swallace/coloc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 凌晨0:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chr1swallace/coloc] Confusing results when using beta and varbeta in coloc.abf() (#43)





 that depends which coloc function you are using? 
 ________________________________
