### ISSUE TITLE
error in coloc.signals

### ISSUE THREAD

**Issue by valborgg** [chr1swallace/coloc#44]
Hello,

I am having some issues with the newly implemented conditional analysis (coloc.signals). I am running this on multiple loci and most of the time it works fine, however in some cases I get an error message about the beta containing missing values, although there are none. 

In one example I tried splitting up the dataframe containing the input data to find the SNP causing the error. Strangely when trying rows 1:2000 I get the error, however when running rows 1:1000 or 1001:2000 it works.

I also can run the coloc.abf() function on the same datasets without any problems. 

The error message looks like this:
> colocres_cond = coloc.signals(df1, df2, p12=1e-5, LD=ld, method="cond", pthr=5e-8, mode="allbutone", maxhits=3)
approximating linear analysis of binary trait
quality of linear approximation (ideal is 1): 1.1913
**Error in check.dataset(x, req = c("beta", "varbeta", "MAF")) :
  dataset : beta contains missing values**
In addition: Warning messages:
1: In sdY.est(vbeta = varbeta, maf = MAF, n = N) :
  estimating sdY from maf and varbeta, please directly supply sdY if known
2: In bin2lin(D) : linear approx quality is not good

The beta and varbeta for the two datasets look like this:
> summary(df1$beta)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.673529 -0.029262  0.006979 -0.009623  0.034412  0.319705
> summary(df1$varbeta)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.0003323 0.0004039 0.0006114 0.0015925 0.0017810 0.0092896
> sum(is.na(df1$beta))
[1] 0
> sum(is.na(df1$varbeta))
[1] 0

> summary(df2$beta)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.
-0.0890000 -0.0086000  0.0003000  0.0008649  0.0100000  0.2600000
> summary(df2$varbeta)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
3.600e-05 4.761e-05 7.225e-05 2.250e-04 2.250e-04 4.410e-02
> sum(is.na(df2$beta))
[1] 0
> sum(is.na(df2$varbeta))
[1] 0

Any help on this would be appreciated.

**Comment by chr1swallace** [comment]
I have found there are numerical issues occasionally in the conditional analysis.  I have recently updated the check_dataset() function which can now better detect any data issues, and also suggest switching to a SuSiE based analysis, rather than conditioning, please see https://chr1swallace.github.io/coloc/articles/a06_SuSiE.html
