### ISSUE TITLE
Coloc.abf does not output probabilities in R

### ISSUE THREAD

**Issue by mirunabarbu8** [chr1swallace/coloc#45]
Dear Chris

I am trying to run coloc.abf on 2 datasets. I input p-values and N samples for both (one is a case-control study), as well as the MAF (taken from one of the studies). The total N SNPs is 1,558,262. When I run coloc.abf this is the output: 

PP.H0.abf PP.H1.abf PP.H2.abf PP.H3.abf PP.H4.abf 
      NaN       NaN       NaN       NaN       NaN 
[1] "PP abf for shared variant: NaN%"

So essentially it is unable to calculate the posterior probabilities. 

I tried with subsets of the same data, and it works - so I get the probabilities if I run for, say, 1,000 SNPs, and it does so for multiple randomly-selected rows - but I want to investigate the entire list.

Would you be able to let me know why this happens? I checked the results of coloc.abf and it provides me with data on each SNP, but not the probability. I am looking forward to your reply.

Best
Miruna

**Comment by chr1swallace** [comment]
Can you show me str() for each list you pass to coloc.abf?

Also, what version do you have installed?

⁣http://chr1swallace.github.io​

**Comment by mirunabarbu8** [comment]
Dear Chris

Thank you for the quick answer! I merged my 2 datasets before running coloc.abf so they are in the same dataframe. The columns I am using are: 

data.frame':	1558262 obs. of  41 variables:
 $ name       : Factor w/ 8085999 levels "rs10","rs1000000",..: 37 37 37 71 71 71 248 397 397 397 ... # SNPs
 $ Freq1      : num  0.903 0.903 0.903 0.587 0.587 ... # MAF
 $ P.value    : num  0.711 0.711 0.711 0.956 0.956 ... # P-value for variable 1 
 $ pval       : num  5.67e-34 1.12e-16 5.59e-33 0.00 2.88e-315 ... # P-value for variable 2

I am working in R version 3.6.3 and coloc version 3.2-1

**Comment by chr1swallace** [comment]
I suspect you may have some missing value somewhere.  Could you try running the check.dataset function defined here https://github.com/chr1swallace/coloc/blob/susie/R/check.R on each dataset you pass to coloc?

However you also seem to be running 1.5 million SNPs. Coloc is designed to test whether two traits share a causal variant in a region of the genome, typically 1000ish SNPs. It doesn't automatically spilt a whole genome into regions.

You need to first identify the region (s) you want to assess for colocalisation and then test each in turn.

⁣http://chr1swallace.github.io​

**Comment by mirunabarbu8** [comment]
Hi Chris

Yes, I am trying to run coloc for multiple regions - I have now split the 1.5 million SNPs dataset by region and it works, so thank you very much!!

I did have a further methodology-related question. One of my datasets contains mQTL data, and contains p-value results for the same SNP associated with multiple CpG. Would you recommend selecting the minimum-pvalue for each SNP that has associations with multiple CpGs? It sounds like the most feasible option, but I am not sure if I should randomly select these instead or go for the most significant association.

Thank you once again for the help!

**Comment by mirunabarbu8** [comment]
Hi Chris

Even when splitting by region, I got NaN for some results - so I decided to use beta, varbeta (calculated as standard error^2), MAF, type, and s (where there is a case-control dataset). The results are massively different from the analysis using p-values, but there is no NaN for any genomic region when running with these variables instead. 

Do you have any troubleshooting for me to check whether the results using beta and varbeta are the correct ones? I am confident they are more reliable than the analysis using pvalues, however I'd like to make sure. 

Thank you!

**Comment by chr1swallace** [comment]
beta and varbeta is definitely preferred if they are available.  we try
and approximate the same quantities from p values, but it is an
approximation.

I haven't seen you data so I don't know what the issue is.  you could
check
- that p values match what you would expect from beta and varbeta
- that p values are all > 0, < 1 - ie no p values are exactly 0 / NA /
infinite
- that MAF, N and s are right

**Comment by mirunabarbu8** [comment]
Dear Chris

Thank you for the comment. I've checked beta and varbeta and they look correct. I wondered if I could check with you a methodology-related question. Here is what my data looks like: 

SNP | Beta1 | Beta2
    -- | --       | --
rs10000057 | 0.0022 | -0.1841002
rs10000057 | 0.0022 | -0.1268973
rs10000057 | 0.0022 | 0.1811976
rs10000116 | -0.0002 | -0.6182259
rs10000116 | -0.0002 | 0.3345903

As you can see, for trait2 (Beta2) the same SNP is associated with multiple CpGs (taken from mQTL analysis), so has multiple beta values per association. However, when running coloc.abf, the same SNP will be repeated (while for trait1 it is the same Beta, for trait2, the Beta changes based on individual CpG association). I wondered if I should keep all associations when I run coloc.abf? Would this introduce noise (as the same SNP is analysed multiple times)? Or would you recommend selecting e.g. the SNP with the highest Beta for trait2? 

I ran coloc.abf with only the most significantly associated SNP and also with all SNP associations included, and results are somewhat different (one region goes from 95% PP of shared SNP to 71% PP of shared SNP, and other regions previously >80% are now very low %). 

Thank you!

**Comment by chr1swallace** [comment]
There should be only one beta per snp per dataset, coloc is designed to work with dense summary data for one pair of datasets.  Please see https://chr1swallace.github.io/coloc/articles/a02_data.html which might help you understand about data requirements.
