### ISSUE TITLE
Output SNP.PP.H3 from coloc.abf

### ISSUE THREAD

**Issue by alxdrcirilo** [chr1swallace/coloc#47]
Hi there! 

Thank you very much for this package. It's very convenient to use.

At the moment, I'm trying to have an additional column that would be the probability of H3 (i.e. **SNP.PP.H3**) per SNP. The coloc.abf function only outputs **SNP.PP.H4.** I tried looking into the source code (specifically the _coloc.abf_ function and the _combine.abf_ internal function) in an attempt to add some lines that would include the aforementioned column to my results, but alas, to no avail. Could you maybe help me with this or point me in the right direction? Any help would be greatly appreciated!

**Comment by chr1swallace** [comment]
Dear Alexandre,

the SNP.PP.H3 is a property of each pair of SNPs, and in fact isn't
calculated directly.

What is it you wish to use the per SNP pair H3 probs for?

C

**Comment by alxdrcirilo** [comment]
Hello Chris,

Thank you for the reply.

In essence, we would like to assess whether MR (Mendelian randomization), looking at methylation and nearby histone modification sites, could differentiate between these two epigenetic mechanisms. If they are instrumented by the same SNP (i.e. H4) then you would not expect differing results regardless of whether you intended to instrument methylation or histone modification. However, if we feel confident that the underlying causal variants are distinct (i.e. H3), then we may be able to use MR to establish whether methylation or histone modifications are on the causal pathway to our outcome.

May I ask how is the SNP.PP.H3 property extracted?

Looking forward to your feedback and thank you for your help!

**Comment by chr1swallace** [comment]
SNP.PP.H4 is already returned.  SNP.PP.H4 is not calculated.  But if you are confident in H3, I would simply finemap each dataset independently and take the posterior probabilities from that.
