### ISSUE TITLE
error when running coloc.SuSie

### ISSUE THREAD

**Issue by schavezchavez** [chr1swallace/coloc#49]
Dear chris,

Thanks a lot for the new SuSie colocalization tool!
I have been trying to get it running to perform colocalization analysis.
I got my data sets checked by the check.dataset function, and they were found correct (NULL exit).
I then tried to run coloc.susie but i keep getting the error below. This error results in an empty results object. 
**running iterations: 100
	converged: TRUE
running iterations: 100
	converged: TRUE
Warning messages:
1: In (function (z, R, maf = NULL, maf_thresh = 0, z_ld_weight = 0,  :
  The z_ld_weight > 0 feature is under development.
2: In (function (z, R, maf = NULL, maf_thresh = 0, z_ld_weight = 0,  :
  The z_ld_weight > 0 feature is under development.**

i was wondering if you know how to troubleshoot this.

Thanks in advance,

**Comment by chr1swallace** [comment]
Hi Sergio, that's a warning not am error.

What's the output of using runsusie() on each of your datasets?

C

⁣http://chr1swallace.github.io​

**Comment by schavezchavez** [comment]
Hi Chris,
when running runsusie i get the same warning. i see for one dataset (qtl data - S3) i get some results, but for my gwas dataset (S4) i don't get any output. see below
> summary(S3)
Variables in credible sets:
 variable variable_prob cs
       34     1.0000000  2
       29     0.9640969  1
       35     0.6013686  1
       39     0.6013686  1
       38     0.5438996  1
Credible sets summary:
cs cs_log10bf cs_avg_r2 cs_min_r2    variable
 2  115.51769 1.0000000 1.0000000          34
 1   85.59643 0.9999991 0.9999973 29,35,38,39
> summary(S4)
Variables in credible sets:
[1] variable      variable_prob cs           
<0 rows> (or 0-length row.names)
Credible sets summary:
data frame with 0 columns and 0 rows

**Comment by chr1swallace** [comment]
It seems Susie doesn't find any credible sets. What do your p values look like for that dataset, is there a signal to be found?

⁣http://chr1swallace.github.io​

**Comment by schavezchavez** [comment]
Yeah. i am not completely familiar with this kind of analyses. In mijn Gwas dataset i have all the snps from one locus and they all have genome wide significant p values, as well as being all in very high LD and having more or less the same beta. I have in my qtl dataset 40ish snps and in my gwas i have 160 snps. all the 40 snps from the qtl dataset overlap with gwas dataset btw. do you think i am lacking power to do this kind of analysis? or something else influencing it?

**Comment by chr1swallace** [comment]
Then may I suggest you start here 
https://chr1swallace.github.io/coloc/articles/a02_data.html with some
description of how to prepare data for coloc?

**Comment by schavezchavez** [comment]
Oke. thank you very much Chris. I will check it out.
