### ISSUE TITLE
Inconsistent test data results with demo by using runsusie() 

### ISSUE THREAD

**Issue by shengzheBian** [chr1swallace/coloc#51]
Hello,

    I am testing the new method of coloc by reference artical “https://chr1swallace.github.io/coloc/articles/a06_SuSiE.html”. 
    
    The result of coloc.abf() is consistent with article, while the result of runsusie() is not.（I have uploaded the codes and result info）

    I am very confused about the above situation，and is this caused by the r package version? My Coloc version is  5.0.0.9002 and susieR is 0.11.7. I would be very grateful if you could help me.
 
![图片](https://user-images.githubusercontent.com/66250284/115141806-daa59c80-a070-11eb-9c47-b4fab1f4b5da.png)
![图片](https://user-images.githubusercontent.com/66250284/115141882-4982f580-a071-11eb-9447-9831ed54f660.png)
![图片](https://user-images.githubusercontent.com/66250284/115141888-51db3080-a071-11eb-9eaf-b80ae569b5f9.png)

**Comment by chr1swallace** [comment]
Dear shengzheBian,

It looks like the warning you see about z_ld_weight is a new message
from susieR and I need to update my susieR library and rerun.

Thank you for the heads up,

Chris

**Comment by chr1swallace** [comment]
runsusie now updated and doesn't use z_ld_weight
