### ISSUE TITLE
Set the maximum number of iterations to a lower amount

### ISSUE THREAD

**Issue by clagiamba** [chr1swallace/coloc#52]
In the "runsusie" function, currently the "max_iter" is set to 100, is it possible to set it to a smaller amount?

**Comment by chr1swallace** [comment]
the code could be extended to do this. What would be the benefit?

**Comment by clagiamba** [comment]
Thank you! 
The benefit would be to do a quicker scan of many loci at least initially. 
Some more complex loci take a very long time and do not converge anyway after 100 iterations...

**Comment by chr1swallace** [comment]
But see lines 236-239 in 
https://github.com/stephenslab/susieR/blob/master/R/susie_ss.R

The algorithm quits on convergence.

And then from line 390 
https://github.com/chr1swallace/coloc/blob/main/R/susie.R you'll see
that runsusie() repeatedly calls susie_rss() until convergence. 

Do you actually want to get unconverged solutions returned?

**Comment by clagiamba** [comment]
Yes exactly, returning "unconverged" after X trials, so that if a locus takes too long I can re-submit independently in case, and have results for faster less complex loci. Does that make sense for others users as well?

**Comment by chr1swallace** [comment]
Then I don't think you want to mess with maxit, but want a new
parameter, say "repeat_until_converged"?

If set to FALSE, I could just return an error message "not converged" -
or do you want the unconverged object?

**Comment by clagiamba** [comment]
Ok I see, then maybe setting a limit to the function:

"And then from line 390
https://github.com/chr1swallace/coloc/blob/main/R/susie.R you'll see
that runsusie() repeatedly calls susie_rss() until convergence."

and yes, returning a "not converged" in case would be great. 
This is just to limit computation time for more complex loci to be treated separately. If you think it is useful for others.

**Comment by chr1swallace** [comment]
added repeat_until_convergence option to runsusie()
