### ISSUE TITLE
coloc.susie vs coloc.abf

### ISSUE THREAD

**Issue by arushiv** [chr1swallace/coloc#54]
Hi Chris,

I've been testing out coloc.susie to look for colocalization between various trait GWAS vs molecular QTL signals using UKBB as the reference panel. I've found the coloc.susie to be really useful at many loci that clearly have multiple independent signals - thanks for this functionality.  One thing I wanted to pick your brain on -

Sometimes, SuSiE doesn't identify any credible sets for a trait (even after lowering the coverage and min_abs_corr parameters), usually when there’s a GWAS/QTL association identified but the signal is weak - we just use coloc.abf in that case. In other cases where SuSiE does identify one or more signals - I compared PP H4 from coloc.susie (best PP H4 among all pairs) vs coloc.abf for the same region. Attached is the plot for type 2 diabetes GWAS vs chromatin accessibility QTL in our tissue of interest, colored by if SuSiE identified one signal for each trait or more than one signal for a trait. Apart from cases where coloc.susie clearly identifies relevant signals and colocalization, coloc.abf gives somewhat higher PP H4 values, often in regions where SuSiE identified only one signal per trait. Is this expected? I would think that SuSiE should help get a clean credible set so PP H4 from coloc.susie should be used regardless of how many signals were identified. On the other hand, we are using a reference panel for SuSiE which can be messy. Would you suggest using coloc.abf where there are clearly single signals for both traits? Or a more manual, visual inspection at each locus of interest?

[fig.pp_comparison1.pdf](https://github.com/chr1swallace/coloc/files/6562999/fig.pp_comparison1.pdf)

**Comment by chr1swallace** [comment]
Hi @arushiv apologies for the late reply. I don't know that I yet have enough experience to make a definitive recommendation. I know SuSiE can sometimes get stuck in a local optimum, so if I am confident there is only one causal variant per trait, I would trust coloc.abf because there is no risk of this happening.  But I don't have evidence to support that coloc.abf will be better, this is just from my understanding of how the methods work.

**Comment by arushiv** [comment]
Hi Chris, 

Yeah, makes sense. Thanks!
