### ISSUE TITLE
Susie parameters

### ISSUE THREAD

**Issue by Zepeng-Mu** [chr1swallace/coloc#55]
Hi, in the documentation of `runsusie` it says the default for coloc are 
```
arguments passed to susie_rss. In particular, if you want to match some coloc defaults, set

prior_variance=0.2^2 (if a case-control trait) or (0.15/sd(Y))^2 if a quantitative trait

estimate_prior_variance=FALSE
```

But it seems that in the code below, these parameters are not set as above
https://github.com/chr1swallace/coloc/blob/a2825b8daf8230724525ef20ab5fdb05af936205/R/susie.R#L409-L410

I think the PIP from this current setup, which is the default `susie_rss`, seems to make more sense compared to using `prior_variance=0.2^2` and `estimate_prior_variance=FALSE`.

Which parameters do you exactly recommend using for COLOC? 

Thanks!

**Comment by chr1swallace** [comment]
The arguments you pass from ... are passed to susie_rss as susie_args.
