### ISSUE TITLE
Encounter "dataset 1: lengths of inputs don't match error"

### ISSUE THREAD

**Issue by shangl02** [chr1swallace/coloc#60]
Hi, I ran into this error after updated a few other packages.
The script and data file ran ok yesterday, but failed with this error after the package update.
```
Error in check_dataset(d = dataset1, 1) :
  dataset 1: lengths of inputs don't match:
Calls: coloc.abf -> check_dataset
Execution halted
```

script
`r<-coloc.abf(dataset1 = list(pvalues=df1$pvalues, N=df1$N, MAF=df1$MAF, beta=df1$beta, varbeta=df1$varbeta, type=convertType(dataType1), s=df1$s, snp=df1$snp), dataset2 = list(pvalues=df2$pvalues, N=df2$N, MAF=df2$MAF, beta=df2$beta, varbeta=df2$varbeta, type=convertType(dataType2), s=df2$s, snp=df2$snp), p1=p1c, p2=p2c, p12=p12c)
`

Any suggestions?

**Comment by shangl02** [comment]
Thanks @chr1swallace. I guess my question is actually about the the back-compatibility. 
Same command, same input file, failed on latest version 5.1, but success in version 3.1/3.2

**Comment by chr1swallace** [comment]
I can't see your data. I suspect there was an issue with your data that wasn't picked up on older version. Can you show me the str() of the datasets you are passing? Do the lengths match?

https://chr1swallace.github.io


________________________________
