### ISSUE TITLE
choosing an optimal LD reference panel for multi-ancestry GWAS 

### ISSUE THREAD

**Issue by ccrobertson** [chr1swallace/coloc#63]
Dear Chris,

This is not a software issue, but a solicitation of your thoughts on best practices. If you'd prefer I submit this type of question elsewhere (e.g., by email), please let me know!

I am running colocalisation analysis using GWAS summary statistics based on a meta-analysis of association analyses from different major ancestral populations (one from European ancestries, one from African Americans, and one from East Asian ancestries). I do have access to individual level data from each analysis, so I could calculate LD matrices within each group (or across all groups). 

I am wondering if you have considered this situation, and if you have any recommendations for what the best LD matrix would be in this scenario.

Thanks for your thoughts.
Cassie

**Comment by chr1swallace** [comment]
Hi Cassie,

fine to use issues for this, thank you.

It's not something I have considered in detail, but my thoughts are
that an accurate LD matrix is important, and the in sample LD matrix is
probably the most accurate you will get.  Thus I would calculate an LD
matrix across all groups, as that corresponds to the meta analysis
results.

Does that make sense?

C

**Comment by ccrobertson** [comment]
Hi Chris,

Yes, that makes sense. Thanks for the advice.

And in the setting where one does not have access to individual level data, would you try to approximate the GWAS cohort as best as possible? For example, if the GWAS was a meta-analysis of Northern European and East Asian cohorts, you would create an LD matrix with both Northern European and EAS samples from 1000 Genomes?

Thanks again.
Cassie

**Comment by chr1swallace** [comment]
I think that's what I would do, but as I say this is not an area I have explored in much depth

https://chr1swallace.github.io


________________________________

**Comment by ccrobertson** [comment]
I understand. Unexplored territory! Thanks again for you thoughts.
