### ISSUE TITLE
"prior variance is unreasonably large" error when using runsusie()

### ISSUE THREAD

**Issue by JFF1594032292** [chr1swallace/coloc#64]
Hi Chris,
    I'm using the coloc 5 version to perform colocalization on  GWAS dataset and an eQTL dataset. However, when I  performed the fine-mapping by runsusie(), some regions reported "The estimated prior variance is unreasonably large" error. 
![image](https://user-images.githubusercontent.com/49577864/143797997-66005e8d-ca80-42eb-ae9f-e8e8a794e1d8.png)
I check the alignment and the check_alignment() plot seems good as shown below.
![image](https://user-images.githubusercontent.com/49577864/143798042-8eb6ddf8-fc42-410c-89db-ec4426cba270.png)
I also check the manhattan plot and I thought there is nothing abnormal.
![image](https://user-images.githubusercontent.com/49577864/143799484-275de96d-8a7b-47bd-9935-48729b73c421.png)
By the way, I run runsusie() for about 900 regions, only 9 regions reported this error. All these 9 regions contain extremely significant P values (top P< 1e-20), this was the only common point I found for them.
I don't know if I miss some important process, or something else.
Thanks!

**Comment by chr1swallace** [comment]
This error arises from susie itself. It means the estimated prior variance is larger than would be expected by the rule of thumb variance < 10 * max(abs(z))^2. It can be bypassed by passing `check_prior=FALSE`, but I'm afraid I have no idea if that is a sensible thing to do.

**Comment by giuseppe-fanelli** [comment]
Hi, does varbeta correspond to (standard error)^2, right? I estimated varbeta starting from standard errors and I got the same error..

**Comment by drarauch** [comment]
Hi Chris, I have similar issues, that the estimated prior variance is too large. I performed the runsusie command with the `check_prior=FALSE` option, however runsusie does not reach convergence. It starts with 1e2, then 1e4, then 1e6 and 1e8 iterations. So I run `S3=runsusie(D3,check_prior=FALSE, maxit=1000,repeat_until_convergence=F )` instead. This of course just leads to failing of the algorithm, however the error message indicates to check for consistency between summary statistics and LD matrix.
Does it mean that I won't be able to get a coloc analysis for those regions at all?
Best, Alex

**Comment by chr1swallace** [comment]
It means susie is failing for those regions.  This can also happen when
there is a mismatch with LD (eg alleles ordered differently).  If you
can't run susie, coloc.abf is nearly as good if your goal is to find
evidence for H4 if it exists.

**Comment by chr1swallace** [comment]
yes, varbeta = se.beta^2

**Comment by albert-ying** [comment]
I encountered the same problem here. I'm wondering what is the general suggestion in this scenario? Would you suggest to run susie with `check_prior=F`, or just `run_coloc.abf`?

**Comment by chr1swallace** [comment]
susie is very sensitive to mismatch between LD matrices and the summary data.  If you don't have a good match, I fall back on coloc.abf
