### ISSUE TITLE
check_dataset

### ISSUE THREAD

**Issue by MoMaz123** [chr1swallace/coloc#72]
Hi, I am trying  to  use   my.res <- finemap.abf(dataset=D1,p1 = 1e-04), 
now  preparing  the  dateset, with 

beta <- read.csv("C:/Users/xxxx/Desktop/beta.csv")
varbeta <- read.csv("C:/Users/xxxx/Desktop/varbeta.csv")
MAF <- read.csv("C:/Users/xxxx/Desktop/MAF.csv")
LD  <- read.csv("C:/Users/xxxx/Desktop/LD.csv", row.names=1)

list_of_df <- list(beta,varbeta, "N" = 18000,"sdY" = 7,"type" = 'quant', MAF, LD)

names(list_of_df) <- c("beta","varbeta", "N" = 18000,"sdY" = 7,"type" = 'quant', "MAF", "LD")

check_dataset(list_of_df)

but having this  error

Error in check_dataset(list_of_df) : 
  dataset : MAF should be a numeric, strictly >0 & <1

please advise, thanks.

**Comment by chr1swallace** [comment]
It says that some of your MAF values are either not numeric or are <=0
or are >= 1

**Comment by MoMaz123** [comment]
thanks, 
that inst accurate because:

> str(MAF)
'data.frame':	100 obs. of  1 variable:
 $ EA_FREQ: num  0.000833 0.005551 0.002558 0.13733 0.000172 ...

right?

**Comment by chr1swallace** [comment]
MAF is supposed to be of class numeric, you have a data.frame

**Comment by MoMaz123** [comment]
Thanks indeed, now I have  done:

MAF <- as.vector(MAF [,1])
str(MAF)

also changed the  LD to  matrix        LD=data.matrix(LD)
now I am having this error, 

> check_dataset(list_of_df)
Error in check_dataset(list_of_df) : 
  dataset : lengths of inputs don't match:

**Comment by MoMaz123** [comment]
they all having the same length, 

> str(beta)
'data.frame':	100 obs. of  1 variable:
 $ BETA: num  0.2305 -0.0634 0.012 0.0232 -0.5869 ...
> str(varbeta)
'data.frame':	100 obs. of  1 variable:
 $ SE: num  0.2474 0.0762 0.1222 0.0154 0.4904 ...
> str(MAF)
 num [1:100] 0.000833 0.005551 0.002558 0.13733 0.000172 ...
> dim(LD)
[1] 100 100

**Comment by chr1swallace** [comment]
what is length(beta)?

**Comment by chr1swallace** [comment]
which is not the same as length(MAF). which is what the error says

**Comment by MoMaz123** [comment]
Great thanks for pointing out, 
how can I solve this issues, please.

**Comment by MoMaz123** [comment]
that solved, now  another one  is  apear, 

Error in check_dataset(dataset, "") : LD rownames != colnames

**Comment by MoMaz123** [comment]
beta <- read.csv("C:/Users/x/Desktop/beta.csv")
str(beta)
length(beta)

beta <- as.vector(beta [,1])

varbeta <- read.csv("C:/Users/x/Desktop/varbeta.csv")
str(varbeta)
length(varbeta)

varbeta <- as.vector(varbeta [,1])


MAF <- read.csv("C:/Users/x/Desktop/MAF.csv")

MAF <- as.vector(MAF [,1])
str(MAF)
class(MAF)
length(MAF)

LD  <- read.csv("C:/Users/x/Desktop/LD.csv", row.names=1)
LD=data.matrix(LD)
dim(LD)




list_of_df <- list(beta,varbeta, "N" = 18000,"sdY" = 7,"type" = 'quant', MAF, LD)

names(list_of_df) <- c("beta","varbeta", "N" ,"sdY" , "type" , "MAF", "LD")

check_dataset(list_of_df)


having this error, 

> check_dataset(list_of_df)
Error in check_dataset(list_of_df) : LD rownames != colnames

**Comment by MoMaz123** [comment]
but they have the exact same name, Rows and Columns in the LD

**Comment by chr1swallace** [comment]
well the error says they don't. did you check?
identical(rownames(LD),colnames(LD))

**Comment by MoMaz123** [comment]
Great thanks, it's done now.
just last question, the SNPs with the highest PP (SNP.PP) are the top hit?
Thanks, mo

**Comment by chr1swallace** [comment]
assuming H4 is true

**Comment by MoMaz123** [comment]
sorry, what is H4?

**Comment by chr1swallace** [comment]
https://chr1swallace.github.io/coloc/articles/a03_enumeration.html
