### ISSUE TITLE
A possible typo in "data structure" wiki?

### ISSUE THREAD

**Issue by Ojami** [chr1swallace/coloc#74]
Hi,

[Here](https://chr1swallace.github.io/coloc/articles/a02_data.html) under section **What if I don’t have sdY?**:

> Otherwise coloc can estimate it, but **_not_** needs MAF and sample size information too.

Is this **not** supposed to be there (sorry for being pedantic)? 

Best/O.

**Comment by chr1swallace** [comment]
it is not! (supposed to be there) - thanks
