### ISSUE TITLE
dependency irlba requires R >= 3.6.2

### ISSUE THREAD

**Issue by mcolosimo-p4** [chr1swallace/coloc#75]
It seems in the last two months, https://github.com/bwlewis/irlba was updated to require R >= 3.6.2. https://github.com/stephenslab/mixsqp depends on irlba, so that now makes coloc depend on R >= 3.6.2. I've also created an issue with mixsqp about this bump in the required R version

**Comment by chr1swallace** [comment]
thank you. I think this dependency should be mentioned in mixsqp, not coloc.
