### ISSUE TITLE
SNP.PP.H4

### ISSUE THREAD

**Issue by Filago4** [chr1swallace/coloc#76]
Hello,
I have a short question:
Here:
https://chr1swallace.github.io/coloc/articles/a03_enumeration.html
it says that SNP.PP4.H4 is the "posterior probabilities for each SNP to be causal conditional on H4 being true".

Does "causal" mean "shared causal" in this context?

Many thanks for your help :)

**Comment by chr1swallace** [comment]
yes, shared causal
