### ISSUE TITLE
Clarification of `null_weight` argument passed to `susie_rss()`

### ISSUE THREAD

**Issue by jdblischak** [chr1swallace/coloc#77]
**Quick summary:** I am attempting to run SuSiE myself and then pass the returned SuSiE objects directly to `coloc.susie()`. Do I need to set `null_weight` to a non-`NULL` value when running SuSiE?

## Background

The documentation for the argument `p` of [`runsusie()`](https://chr1swallace.github.io/coloc/reference/runsusie.html) states that the default of `p=NULL` will result in passing a non-NULL value to the argument `null_weight` of `susie_rss()`:

https://github.com/chr1swallace/coloc/blob/f9635f56bad8a2fef69aceee8f4eb30b62a8e7a0/R/susie.R#L406-L412

Correspondingly, the [SuSiE vignette](https://chr1swallace.github.io/coloc/articles/a06_SuSiE.html) states ([source](https://github.com/chr1swallace/coloc/blob/5e3a50201a304addfcfa8f09813d19c4c4127a3f/vignettes/a06_SuSiE.Rmd#L80)):

> `runsusie()` is a wrapper around `susieR::susie_rss()`.  It sets the null_weight parameter - this must be non-zero or we cannot back calculate Bayes factors needed for coloc

From investigating the GitHub repo, this section of the vignette was prompted by the discussion in https://github.com/chr1swallace/coloc/issues/46#issuecomment-813954242:

>   I realised we can't set null_weight=NULL, because I need SuSiE to give me a posterior probability for the null hypothesis so I can back-calculate the Bayes factors needed for coloc.

However, the code appears to be out of sync from the documentation above, because `null_weight` is no longer set by default:

https://github.com/chr1swallace/coloc/blob/ac928af483561ac3d3b3d91b5f631f8679505f89/R/susie.R#L484-L490

And the documentation for the argument `back_calculate_lbf ` of [`coloc.susie()`](https://chr1swallace.github.io/coloc/reference/coloc.susie.html) now states that back-calculating the BFs is for testing only:

https://github.com/chr1swallace/coloc/blob/ac928af483561ac3d3b3d91b5f631f8679505f89/R/susie.R#L99-L102

**Comment by chr1swallace** [comment]
thanks for spotting this! The vignette is out of date. The null_weight
was needed before, but now susie returns bayes factors directly so I
don't need this hack.

**Comment by jdblischak** [comment]
Also relevant to the coloc documentation is that the SuSiE authors are planning on changing the default for `null_weight` from `NULL` to `0` https://github.com/stephenslab/susieR/issues/153

**Comment by jdblischak** [comment]
Looking at the code again for `runsusie()` (and `coloc.susie()`), it appears that the argument `p` for `runsusie()` is completely ignored. Users have to explicitly set `null_weight` in order to have any affect on `susie_rss()`.
