### ISSUE TITLE
How to find H0 to H3 from the coloc.abf output for each snp

### ISSUE THREAD

**Issue by zillurbmb51** [chr1swallace/coloc#85]
Hi,
The coloc.abf gives us summary (PP for H0-4) and dataframe with the following columns: `"snp"	"position"	"V.df1"	"z.df1"	"r.df1"	"lABF.df1"	"V.df2"	"z.df2"	"r.df2"	"lABF.df2"	"internal.sum.lABF"	"SNP.PP.H4"`

How could we find the PP for other hypothesis (H0-3) for each snp?

**Comment by chr1swallace** [comment]
H1, h2, use finemap.abf. hp doesn't correspond to any individual snp. If you believe h3 is true, then I would use the per trait per snp results from finemap.abf to infer the most likely causal variants for each.

https://chr1swallace.github.io
________________________________
From: zillurbmb51 ***@***.***>
Sent: Sunday, May 8, 2022 3:29:59 PM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] How to find H0 to H3 from the coloc.abf output for each snp (Issue #85)


Hi,
The coloc.abf gives us summary (PP for H0-4) and dataframe with the following columns: "snp" "position" "V.df1" "z.df1" "r.df1" "lABF.df1" "V.df2" "z.df2" "r.df2" "lABF.df2" "internal.sum.lABF" "SNP.PP.H4"

How could we find the PP for other hypothesis (H0-3) for each snp?
