### ISSUE TITLE
Error while running moloc

### ISSUE THREAD

**Issue by JayshreeAdvani** [chr1swallace/coloc#86]
I am trying to run moloc and I am getting this error 
Error in { : 
  task 1 failed - "task 1 failed - "object 'check.dataset' not found""
I have eQTL data, mQTL data and GWAS data

**Comment by JayshreeAdvani** [comment]
I am using coloc as well in my script and using this function coloc:::check.dataset(dataset, i, req = "MAF") and it is giving me error for check.dataset

**Comment by chr1swallace** [comment]
The error suggests you don't have coloc loaded because it can't find the function. How have you installed it?

https://chr1swallace.github.io
________________________________

**Comment by JayshreeAdvani** [comment]
Yes I have installed coloc and load it as a library(coloc) in my R script.

**Comment by chr1swallace** [comment]
well I do not understand.

How are you calling it?

What happens when you type "check.dataset" at the prompt?
