### ISSUE TITLE
method to simulate data doesn't show up at beginning of vignette.pdf

### ISSUE THREAD

**Issue by chr1swallace** [chr1swallace/coloc#9]

**Comment by boxiangliu** [comment]
Has there been any resolution? I would like to know how to simulate data in the vignette too.

**Comment by pwwang** [comment]
Any updates?

**Comment by chr1swallace** [comment]
It's fixed.

**Comment by pwwang** [comment]
Thanks for the reply. I just want to get the idea how it works. It'll be great if you could show part of the data, or format of the data.

Thank you!

**Comment by chr1swallace** [comment]
OK - found it - `sim.data()` now visible at https://chr1swallace.github.io/coloc/articles/vignette.html
