### ISSUE TITLE
HLA imputation and SUSIE

### ISSUE THREAD

**Issue by Richard-Packer** [chr1swallace/coloc#93]
Hi,

Not an issue but a question, could SUSIE be used for colocalisation using in the HLA region if using imputted HLA alleles, there are around 2500 imputted alleles which on previous experiance with co-localisatiopn seems like a small number. I'm just wondering if there is any conceptual issue with the idea?

**Comment by chr1swallace** [comment]
I am not an author of susie. But my experience of the HLA suggests you will struggle to have a perfect matching LD matrix to use the susie summary stats version.  If you have the individual level data, I suspect that would work better?
________________________________
From: Richard-Packer ***@***.***>
Sent: 08 June 2022 09:49
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] HLA imputation and SUSIE (Issue #93)


Hi,

Not an issue but a question, could SUSIE be used for colocalisation using in the HLA region if using imputted HLA alleles, there are around 2500 imputted alleles which on previous experiance with co-localisatiopn seems like a small number. I'm just wondering if there is any conceptual issue with the idea?
