### ISSUE TITLE
Runsusie returns null credible set

### ISSUE THREAD

**Issue by jeji0209** [chr1swallace/coloc#94]
Hello.
When I try runsusie() with a set of SNPs before running coloc.susie(), it ways that my variants have converged at max iterations 100.
However, when I check my result for runsusi() by using summary(susie_result), it returns that I have 0 credible sets, and 0 variables for credible sets.
How can interpret this? 

Thank you.

**Comment by chr1swallace** [comment]
Do you have any strong associations? Perhaps there is no causal variant in the region?

https://chr1swallace.github.io
________________________________
From: jeji0209 ***@***.***>
Sent: Thursday, June 23, 2022 10:05:15 AM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] Runsusie returns null credible set (Issue #94)


Hello.
When I try runsusie() with a set of SNPs before running coloc.susie(), it ways that my variants have converged at max iterations 100.
However, when I check my result for runsusi() by using summary(susie_result), it returns that I have 0 credible sets, and 0 variables for credible sets.
How can interpret this?

Thank you.

**Comment by chr1swallace** [comment]
0.05 is not considered significant in genetic association. what is your minimum p value?
________________________________

**Comment by jeji0209** [comment]
It varies depending on the variant set I am using (none of them are returning a credible set so far), but the lowest one had 0.001.

**Comment by chr1swallace** [comment]
Well you have nothing that would be considered genome wide significant

https://chr1swallace.github.io
________________________________

**Comment by jeji0209** [comment]
Ah okay I understand!
