### ISSUE TITLE
How to interpret coloc.susie results with two different variants in low LD?

### ISSUE THREAD

**Issue by wonjikim11** [chr1swallace/coloc#98]
Hi,

I visited https://github.com/chr1swallace/coloc/issues/84 and figured out how to interpret coloc.susie results with two different variants in high LD.
In most cases, they were in high LD but some were in low LD such as r2=0.5, and I wonder how to interpret this.
Can I interpret this as multiple causal variants?

One more, if I found two colocalizations involving one eQTL and three variants, e.g.
eQTL1 - variant1 & variant2
eQTL1 - variant1 & variant3,
can it be considered one colocalization involving three variants?

Thanks!

**Comment by chr1swallace** [comment]
I think you need to give me more detail.

Are the two Susie variants in the same credible set or different?


What do you mean by your eqtl colocalisations? Coloc doesn't give you a yes/no answer, but a probability. What do the data look like for these traits (use plot_dataset()) and what method of analysis are you using?

https://chr1swallace.github.io
________________________________
From: wonjikim11 ***@***.***>
Sent: Tuesday, August 16, 2022 6:19:07 AM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] How to interpret coloc.susie results with two different variants in low LD? (Issue #98)


Hi,

I visited #84<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchr1swallace%2Fcoloc%2Fissues%2F84&data=05%7C01%7Ccew54%40universityofcambridgecloud.onmicrosoft.com%7C65f14bb703f24665ce3e08da7f46eb80%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637962239813854208%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vDrmOXmfQqoHatdUjxIt%2Br3ijQ3B%2F4Y%2F5GGNGrhSaM0%3D&reserved=0> and figured out how to interpret coloc.susie results with two different variants in high LD.
In most cases, they were in high LD but some were in low LD such as r2=0.5, and I wonder how to interpret this.
Can I interpret this as multiple causal variants?

One more, if I found two colocalizations involving one eQTL and three variants, e.g.
eQTL1 - variant1 & variant2
eQTL1 - variant1 & variant3,
can it be considered one colocalization involving three variants?

Thanks!

**Comment by wonjikim11** [comment]
1. They are in the same credible set.
2. Let me take a look at the plot_dataset(). I used coloc.susie on gwas and eqtl with summary statistics. I wonder if multiple colocalizations sharing a causal variant can be interpreted as a colocalization with multiple causal variants.

**Comment by chr1swallace** [comment]
1 if in the same credible set, they are not two signals
2 suspect this relates to (lack of) power to distinguish signals

https://chr1swallace.github.io
________________________________

**Comment by wonjikim11** [comment]
1. So, in what cases can we conclude that there are multiple causal variants? If they are in the different credible sets?

**Comment by chr1swallace** [comment]
yes
________________________________

**Comment by wonjikim11** [comment]
I got it. Thank you!
